### ISSUE TITLE
Errors on Android don't have a message: `Unknown std::runtime_error error`

### ISSUE THREAD

**Issue by mrousavy** [mrousavy/nitro#382]
### What's happening?

On Android, errors / exceptions don't have a proper message, and always resort to `Unknown T error` (e.g. `Unknown std::runtime_error error`) instead of using it's message (`what()`).

The same goes for `Promise<T>`. 

I can't really figure out why this is happening - my best guess is that there is some ABI issue with the libc++ standard used by Android NDK, and since errors in Nitro are implemented using `std::exception_ptr`, the methods `current_exception()`/`rethrow_exception(..)` are **broken in Android**.
I created an issue in the react-native repo: https://github.com/facebook/react-native/issues/48027

### Reproduceable Code

```tsx
class MyHybrid: public MyHybridSpec {
  // ...
public:
  void someFunc() override {
    throw std::runtime_error("my message!");
  }
};
```

### Relevant log output

iOS ✅:

```shell
MyHybrid.someFunc(): my message!
```

Android ❌:

```shell
MyHybrid.someFunc() threw an unknown std::runtime_error error.
```

### Device

Huawei P10

### Nitro Modules Version

0.18.1

### Nitrogen Version

0.18.1

### Can you reproduce this issue in the Nitro Example app here?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I am using Nitrogen (nitro-codegen)
- [X] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/docs/troubleshooting).
- [ ] I created a reproduction PR to reproduce this issue here in the nitro repo. (See [Contributing](https://nitro.margelo.com/docs/contributing) for more information)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
cc @Szymon20000

**Comment by mrousavy** [comment]
Actually this is a react-native bug, not a Nitro bug. It can be reproduced in a blank new react-native 0.76 or 0.77 app. https://github.com/facebook/react-native/issues/48027

**Comment by jobpaardekooper** [comment]
Since this is a RN bug, do you know any issue number/link on their repo that tracks this?

**Comment by mrousavy** [comment]
yea see my comment directly above yours

**Comment by jobpaardekooper** [comment]
I don't know how I missed that... sorry. Thanks for the reply.

**Comment by iwater** [comment]
this also show on ios platform with react-native@0.76.5
```
Error: `NitroModulesProxy.createHybridObject(...)` threw an unknown std::runtime_error error.
```

**Comment by mrousavy** [comment]
@iwater i cannot reproduce this on iOS - which Nitro version? can you reproduce this in the NitroExample app here?

**Comment by iwater** [comment]
0.20.1，I just use template folder code as library template and add Math code from doc, then got that error message

**Comment by iwater** [comment]
sorry, I just create a new project, it can show detail error message now. That say "Error: NitroModulesProxy.createHybridObject(...): Cannot create an instance of HybridObject "Crypto" - It has not yet been registered in the Nitro Modules HybridObjectRegistry!", and gave some android platform suggestions, "Crypto" was set in nitro.json autolinking part, it there any other setting on ios platform?

**Comment by Nlcke** [comment]
Is `unknown facebook::jni::JniException` error related to this issue? For example:
```
(NOBRIDGE) ERROR  [Error: `Math.throwError(...)` threw an unknown facebook::jni::JniException error.]
```

The Kotlin class is:

```kt
package com.margelo.nitro.math

class HybridMath : HybridMathSpec() {
    override val memorySize = 0L

    override fun throwError() {
        throw Error("THIS IS ERROR!")
    }
}
```

**Comment by mrousavy** [comment]
Yup, same story here.

Unfortunately caused by the new SoLoader merging changes introduced in RN 0.76.

@Nlcke If you can try what @cortinico suggested in [this comment](https://github.com/facebook/react-native/issues/48027#issuecomment-2567699098), that would be a huge help.

**Comment by cortinico** [comment]
> Unfortunately caused by the new SoLoader merging changes introduced in RN 0.76

Has this been confirmed as being the root cause?

**Comment by mrousavy** [comment]
Not 100%, no. Should've phrased this differently. 
But I'm pretty sure we can figure that out if we try your suggestion in your comment.

**Comment by thecynicalpaul** [comment]
I am experiencing the same on iOS.
Simply doing something along the lines of 

```c++
std::shared_ptr<margelo::nitro::Promise<void>> ClassName::asyncMethod() {
  return Promise<void>::async([this]() -> void {
    throw std::runtime_error("GENERIC RUNTIME ERROR");
  });
}
```

Throws an `[Error: Unknown std::runtime_error error.]`. In other cases of actual failures, I get `Unknown St13runtime_error error`.

react-native@0.75.4
nitro@0.22.1

Some info from our podspec:
```podspec
s.pod_target_xcconfig = {
    'USE_HEADERMAP' => 'YES',
    'DEFINES_MODULE' => 'YES',
    'CLANG_CXX_LANGUAGE_STANDARD' => 'c++20',
    'SWIFT_COMPILATION_MODE' => 'wholemodule',
    'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) FOLLY_NO_CONFIG FOLLY_CFG_NO_COROUTINES MINIAUDIO_IMPLEMENTATION MA_NO_RUNTIME_LINKING'
  }

  s.frameworks =
    "Foundation",
    "AVFoundation",
    "AVFAudio",
    "CoreFoundation",
    "CoreAudio",
    "AudioToolbox"
  

  s.subspec "MiniAudio" do |ss|
    ...
    ss.compiler_flags = "-x objective-c -lpthread -lm"
  end
```

**Comment by mrousavy** [comment]
@thecynicalpaul I'd need a repro for that. The NitroExample app tests exactly this code and it works just fine. https://github.com/mrousavy/nitro/blob/41d94a5ddea6243216465aec29331eddf58406d1/packages/react-native-nitro-image/cpp/HybridTestObjectCpp.cpp#L366-L368

**Comment by mrousavy** [comment]
If you pass custom `compiler_flags` you'd likely want to enable `-fexceptions` and `-frtti` tho.

**Comment by ShivamJoker** [comment]
I am also getting the error message: `threw an unknown facebook::jni::JniException error` instead of actual error which I throw in Kotlin.
Hope we can fix this, else it would be really hard to debug any error as a user or developer.

**Comment by shovel-kun** [comment]
Using `react-native@0.80.0-nightly-20250307-1a9adfba1`,  I can confirm that errors have messages now! No idea how to patch for current RN versions though, applying [this commit](https://github.com/facebook/react-native/commit/3132cc88dd46f95898a756456bebeeb6c248f20e) doesn't seem to have changed anything, even after a rebuild.

**Comment by cortinico** [comment]
> I can confirm that errors have messages now! No idea how to patch for current RN versions though, applying [this commit](https://github.com/facebook/react-native/commit/3132cc88dd46f95898a756456bebeeb6c248f20e) doesn't seem to have changed anything, even after a rebuild.

It's not a single commit sadly, it's a rather complicated series of commits.

**Comment by mrousavy** [comment]
Nice to hear it is working in 0.80 now though. Great to see the ecosystem progressing and improving so fast - thanks again @cortinico. ❤

**Comment by KrzysztofMoch** [comment]
I have found this patch to workaround this bug
```diff
diff --git a/node_modules/react-native-nitro-modules/cpp/core/HybridFunction.hpp b/node_modules/react-native-nitro-modules/cpp/core/HybridFunction.hpp
index aefd987..c2e06fb 100644
--- a/node_modules/react-native-nitro-modules/cpp/core/HybridFunction.hpp
+++ b/node_modules/react-native-nitro-modules/cpp/core/HybridFunction.hpp
@@ -23,6 +23,10 @@ struct JSIConverter;
 #include <string>
 #include <type_traits>
 
+#ifdef ANDROID
+#include <fbjni/fbjni.h>
+#endif
+
 namespace margelo::nitro {
 
 using namespace facebook;
@@ -118,6 +122,10 @@ public:
         std::string funcName = getHybridFuncFullName<THybrid>(kind, name, hybridInstance.get());
         std::string message = exception.what();
         throw jsi::JSError(runtime, funcName + ": " + message);
+      } catch (const jni::JniException& exception) {
+        std::string funcName = getHybridFuncFullName<THybrid>(kind, name, hybridInstance.get());
+        std::string message = exception.what();
+        throw jsi::JSError(runtime, funcName + ": " + message);
 #pragma clang diagnostic pop
 #endif
       } catch (...) {
```

But it's still workaround... best would be upgrading to react-native 0.80 once it's released

**Comment by joprice** [comment]
I'm also seeing this from swift as well. I tried running the example app to see if i can repro in isolation, but haven't gotten it to build yet. I also tried the latest rc (4), but had unrelated build issues. Hopefully 80 is released in the near future.

**Comment by mrousavy** [comment]
> I'm also seeing this from swift as well.

This is an Android only bug, this does not happen in Swift. I just tested it again to verify, all tests run on iOS - both C++ and Swift Hybrid Object tests.

**Comment by joprice** [comment]
On ios, I'm seeing these unknown errors when throwing from within a promise like `throw RuntimeError.error(withMessage: "Failed creating recognizer")`. I'll keep digging if it's a different issue.

**Comment by mrousavy** [comment]
This 100% works in the example in Swift here; https://github.com/mrousavy/nitro/blob/88239361578b520adeda69e675ff2e72572b9021/packages/react-native-nitro-image/ios/HybridTestObjectSwift.swift#L262-L266

Can you share your code? Or try to get the example to run and modify on your end. You just need `bun bootstrap` and then open it in Xcode

**Comment by joprice** [comment]
I just got the example to build and all tests pass. The code is private, but if I can minimize the repro, I'll make a repo to share it. I'm comparing the two projects to see if I have any odd configuration that would cause a different result, but it's basically just a simple module created from `npx create-nitro-module@latest`.

**Comment by joprice** [comment]
I've done some debugging, and found that after removing the `#ifdef ANDROID` guard, that branch is hit and the error message is propagated. So it seems that perhaps an rtti issue where a runtime_error is not considered an exception for whatever reason. I'm using static frameworks (due to firebase limitation mentioned in other issues), and perhaps that affects it. I can try using a patch for now until I solve it.

**Comment by mrousavy** [comment]
Fixed in https://github.com/mrousavy/nitro/pull/741 (RN 80+)

**Comment by joprice** [comment]
@mrousavy I've confirmed on ios that this happens when I enable static linking in my project, but still can't narrow it down as to why. I ran the example project again today with static linking and it worked fine, so it's got to be something to do with some other compiler flags being propagated. 

I'd like to provide a repro, but I'm having trouble finding what would even be likely to cause it. I'm currently comparing the compiler settings in pbxproj to see if somehow rtti is being disabled or the wrong std is being used (my only working guesses so far as to why the exception type check isn't being hit). Any tips on where to look would be appreciated as I'm not doing anything too unusual and I assume others will hit this eventually.

**Comment by joprice** [comment]
Turns out this is triggered by a dependency on @shopify/react-native-skia. Digging into why and will post if I can get to the bottom of it.

Repro branch - running the "throwError(error)" test fails after adding @shopify/react-native-skia https://github.com/mrousavy/nitro/compare/main...joprice:nitro:runtime-error

**Comment by mrousavy** [comment]
Hmm interesting, maybe RN Skia has a weird C++ build config setting

**Comment by mrousavy** [comment]
@cortinico as preparations for iOS shipping prebuilt binaries; can we make sure `-frtti` and `-fexceptions` are set for the iOS binaries so we don't run into the same issues?

**Comment by cortinico** [comment]
> [@cortinico](https://github.com/cortinico) as preparations for iOS shipping prebuilt binaries; can we make sure `-frtti` and `-fexceptions` are set for the iOS binaries so we don't run into the same issues?

cc @cipolleschi
